# Generated by Django 5.1.5 on 2025-01-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_remove_menu_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="description",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
